FROM ubuntu:latest
RUN apt-get update && apt-get -y install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config python-all python-all-dev python-all-dbg wget
RUN mkdir /workspace
WORKDIR /workspace

RUN wget http://apache.mirror.amaze.com.au/thrift/0.11.0/thrift-0.11.0.tar.gz && tar -zxvf thrift-0.11.0.tar.gz
RUN cd thrift-0.11.0 && ./configure --without-ruby && make && make install 

ENTRYPOINT ["thrift"]
